### ISSUE TITLE
Automatic launch.json creator doesn't suggest suitable config

### ISSUE THREAD

**Issue by AntonKosenkoDX** [JaneySprings/VSCode.Meteor#1]
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/2052851/203403062-6ec9be65-6072-409a-af76-d76482063704.png">

**Comment by JaneySprings** [comment]
Hello, Anton! Thank you for your message. 

I can't reproduce this bug, could you answer a few questions:
* Extension is activated? Can you see some pickers in bottom statusbar?
* If you add launch.json manually, debug is working?

Best regard,
Meteor Support Team
